server:
  port: 18080

spring:
  application:
    name: 'spring-batch'

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: root
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: create

  batch:
    jdbc:
      initialize-schema: always
      # table-prefix: BATCH_
      # isolation-level-for-create: serializable

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    default-executor-type: batch

